# Configuration file for golangci-lint
# See https://golangci-lint.run/usage/configuration/ for more information

# Options for analysis running
run:
  # Timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
  # Include test files or not, default is true
  tests: true
  # Default concurrency is a available CPU number
  concurrency: 4
  # Exit code when at least one issue was found, default is 1
  issues-exit-code: 1
  # Which dirs to skip: they won't be analyzed;
  skip-dirs:
    - vendor
  # Which files to skip: they will be analyzed, but issues from them won't be reported
  skip-files:
    - ".*\\.generated\\.go$"

# Output configuration options
output:
  # Format: colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number
  # Print lines of code with issue, default is true
  print-issued-lines: true
  # Print linter name in the end of issue text, default is true
  print-linter-name: true

# All available settings of specific linters
linters-settings:
  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: true
  govet:
    # Report about shadowed variables
    check-shadowing: true
  gocyclo:
    # Minimal code complexity to report, 30 by default
    min-complexity: 15
  dupl:
    # Tokens count to trigger issue, 150 by default
    threshold: 100
  goconst:
    # Minimal length of string constant, 3 by default
    min-len: 3
    # Minimal occurrences count to trigger, 3 by default
    min-occurrences: 3
  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US
  lll:
    # Max line length, lines longer will be reported. Default is 120.
    line-length: 120
  goimports:
    # Put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: nauthilus-ui
  gocritic:
    # Enable specific checkers
    enabled-tags:
      - performance
      - style
      - diagnostic
    disabled-checks:
      - commentFormatting # Sometimes we want to use markdown in comments
  wsl:
    # Enforce empty lines between certain statements
    strict-append: true
    allow-assign-and-call: false
    allow-multiline-assign: false
    allow-cuddle-declarations: false
    allow-trailing-comment: false
    allow-separated-leading-comment: false
    force-case-trailing-whitespace: 0
    force-err-cuddling: false
    force-short-decl-cuddling: false
    allow-cuddle-with-calls: ["Lock", "RLock"]
    allow-cuddle-with-rhs: ["Unlock", "RUnlock"]
    require-return-statement-on-separate-line: true
    require-channel-operations-on-separate-line: true

# Linters to run in addition to default ones
linters:
  enable:
    - bodyclose     # Checks whether HTTP response body is closed successfully
    - dupl          # Tool for code clone detection
    - errcheck      # Errcheck is a program for checking for unchecked errors in go programs
    - goconst       # Finds repeated strings that could be replaced by a constant
    - gocyclo       # Computes and checks the cyclomatic complexity of functions
    - gofmt         # Gofmt checks whether code was gofmt-ed
    - goimports     # Goimports does everything that gofmt does and also checks imports
    - gosec         # Inspects source code for security problems
    - gosimple      # Linter for Go source code that specializes in simplifying a code
    - govet         # Vet examines Go source code and reports suspicious constructs
    - ineffassign   # Detects when assignments to existing variables are not used
    - interfacer    # Linter that suggests narrower interface types
    - maligned      # Tool to detect Go structs that would take less memory if their fields were sorted
    - misspell      # Finds commonly misspelled English words in comments
    - nakedret      # Finds naked returns in functions greater than a specified function length
    - prealloc      # Finds slice declarations that could potentially be preallocated
    - staticcheck   # Staticcheck is a go vet on steroids, applying a ton of static analysis checks
    - stylecheck    # Stylecheck is a replacement for golint
    - typecheck     # Like the front-end of a Go compiler, parses and type-checks Go code
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Reports unused function parameters
    - unused        # Checks Go code for unused constants, variables, functions and types
    - whitespace    # Tool for detection of leading and trailing whitespace
    - wsl           # Whitespace Linter - Forces you to use empty lines

  disable:
    - depguard      # Go linter that checks if package imports are in a list of acceptable packages
    - dogsled       # Checks assignments with too many blank identifiers (e.g. x, _, _, _, := f())
    - funlen        # Tool for detection of long functions
    - gochecknoglobals # Check that no global variables exist
    - gochecknoinits   # Checks that no init functions are present in Go code
    - godox         # Tool for detection of FIXME, TODO and other comment keywords
    - gomnd         # An analyzer to detect magic numbers
    - lll           # Reports long lines

# Issues configuration
issues:
  # List of regexps of issue texts to exclude
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - unparam

    # Exclude known linters from partially hard-vendored code,
    # which is impossible to exclude via "nolint" comments.
    - path: vendor/
      linters:
        - all

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
