CREATE DATABASE IF NOT EXISTS nauthilus;

CREATE TABLE IF NOT EXISTS nauthilus.logins (
  ts DateTime64(3, 'UTC'),
  session String,
  service LowCardinality(String) CODEC(ZSTD(3)),
  features LowCardinality(String) CODEC(ZSTD(3)),
  client_ip String,
  client_port String,
  client_net LowCardinality(String),
  client_id LowCardinality(String),
  hostname LowCardinality(String) CODEC(ZSTD(3)),
  proto LowCardinality(String),
  method LowCardinality(String),
  user_agent LowCardinality(String) CODEC(ZSTD(5)),
  local_ip LowCardinality(String),
  local_port String,
  display_name LowCardinality(String),
  account LowCardinality(String),
  username LowCardinality(String),
  password_hash String,
  pwnd_info LowCardinality(String),
  brute_force_bucket LowCardinality(String),
  brute_force_counter Nullable(UInt64),
  oidc_cid LowCardinality(String),
  failed_login_count Nullable(UInt64),
  failed_login_rank Nullable(UInt64),
  failed_login_recognized Nullable(Bool),
  geoip_guid LowCardinality(String),
  geoip_country LowCardinality(String),
  geoip_iso_codes LowCardinality(String),
  geoip_status LowCardinality(String),
  gp_attempts Nullable(UInt64),
  gp_unique_ips Nullable(UInt64),
  gp_unique_users Nullable(UInt64),
  gp_ips_per_user Nullable(Float64),
  prot_active Nullable(Bool),
  prot_reason LowCardinality(String),
  prot_backoff Nullable(UInt64),
  prot_delay_ms Nullable(UInt64),
  dyn_threat Nullable(UInt64),
  dyn_response LowCardinality(String),
  repeating Nullable(Bool),
  rwp Nullable(Bool),
  user_found Nullable(Bool),
  authenticated Nullable(Bool),
  xssl_protocol LowCardinality(String),
  xssl_cipher LowCardinality(String),
  ssl_fingerprint LowCardinality(String),
  latency UInt64,
  http_status UInt16,
  status_msg LowCardinality(String),
  INDEX idx_username username TYPE tokenbf_v1(1024, 3, 0) GRANULARITY 64,
  INDEX idx_account account TYPE tokenbf_v1(1024, 3, 0) GRANULARITY 64,
  INDEX idx_client_ip client_ip TYPE tokenbf_v1(1024, 3, 0) GRANULARITY 64
) ENGINE = MergeTree
ORDER BY (ts)
TTL toDateTime(ts) + INTERVAL 1 WEEK DELETE
SETTINGS index_granularity = 8192;
