export interface YamlExportCommentOptions {
  profileName?: string | null;
  profileVersion?: YamlExportProfileVersion | null;
}

export interface YamlExportProfileVersion {
  version?: number | null;
  source?: string | null;
  createdAt?: string | null;
  createdBy?: string | null;
  comment?: string | null;
  metadata?: Record<string, unknown> | null;
}

const YAML_EXPORT_FORMAT_VERSION = '1';

const normalizeCommentValue = (value: string): string => {
  return value.replace(/[\r\n]+/g, ' ').replace(/\s+/g, ' ').trim();
};

const getMetadataString = (metadata: Record<string, unknown> | null | undefined, ...keys: string[]): string => {
  if (!metadata) {
    return '';
  }

  for (const key of keys) {
    const raw = metadata[key];
    if (typeof raw === 'string') {
      const normalized = normalizeCommentValue(raw);
      if (normalized !== '') {
        return normalized;
      }
    }
  }

  return '';
};

const formatCreatedAt = (rawCreatedAt: string): string => {
  const createdAtDate = new Date(rawCreatedAt);
  if (Number.isNaN(createdAtDate.getTime())) {
    return normalizeCommentValue(rawCreatedAt);
  }

  return createdAtDate.toLocaleString();
};

const redactRepositoryURL = (rawURL: string): string => {
  const sanitizedRaw = normalizeCommentValue(rawURL);
  if (sanitizedRaw === '') {
    return '';
  }

  try {
    const parsed = new URL(sanitizedRaw);

    if (parsed.username || parsed.password) {
      parsed.username = '***';
      parsed.password = '';
    }

    // Avoid leaking potential access tokens from query strings.
    parsed.search = '';
    parsed.hash = '';

    return parsed.toString();
  } catch {
    return sanitizedRaw;
  }
};

const buildVersionCommentLines = (profileVersion: YamlExportProfileVersion | null | undefined): string[] => {
  if (!profileVersion) {
    return [];
  }

  const version = Number(profileVersion.version);
  if (!Number.isInteger(version) || version <= 0) {
    return [];
  }

  const source = typeof profileVersion.source === 'string' ? normalizeCommentValue(profileVersion.source) : '';
  const createdByRaw = typeof profileVersion.createdBy === 'string' ? normalizeCommentValue(profileVersion.createdBy) : '';
  const createdBy = createdByRaw || 'system';
  const createdAtRaw = typeof profileVersion.createdAt === 'string' ? normalizeCommentValue(profileVersion.createdAt) : '';
  const createdAt = createdAtRaw ? formatCreatedAt(createdAtRaw) : 'n/a';
  const comment = typeof profileVersion.comment === 'string' ? normalizeCommentValue(profileVersion.comment) : '';

  const metadata = profileVersion.metadata || null;
  const branch = getMetadataString(metadata, 'branch');
  const filePath = getMetadataString(metadata, 'filePath', 'file_path');
  const commitHash = getMetadataString(metadata, 'commitHash', 'commit_hash');
  const repositoryURL = redactRepositoryURL(getMetadataString(metadata, 'repositoryUrl', 'repository_url'));

  const lines = [
    source ? `# Version ${version} • ${source}` : `# Version ${version}`,
    `# Created: ${createdAt} by ${createdBy}`,
  ];

  if (comment !== '') {
    lines.push(`# Comment: ${comment}`);
  }

  if (branch || filePath || commitHash || repositoryURL) {
    const gitSegments = [branch || '-'];
    if (filePath) {
      gitSegments.push(filePath);
    }
    if (commitHash) {
      gitSegments.push(commitHash);
    }
    if (repositoryURL) {
      gitSegments.push(repositoryURL);
    }
    lines.push(`# Git: ${gitSegments.join(' • ')}`);
  }

  return lines;
};

export const getYamlExportFormatVersion = (): string => YAML_EXPORT_FORMAT_VERSION;

export const buildYamlExportCommentLines = (options: YamlExportCommentOptions = {}): string[] => {
  const lines = [
    '# Generated by Nauthilus UI',
    `# Export format version: ${getYamlExportFormatVersion()}`,
  ];

  const profileName = typeof options.profileName === 'string' ? normalizeCommentValue(options.profileName) : '';
  if (profileName !== '') {
    lines.push(`# Profile: ${profileName}`);
  }

  lines.push(...buildVersionCommentLines(options.profileVersion));

  return lines;
};

/**
 * Prefixes exported YAML with a deterministic metadata comment block.
 * The header is intentionally stable to avoid artificial Git diffs.
 */
export const prependYamlExportComment = (
  yamlContent: string,
  options: YamlExportCommentOptions = {},
): string => {
  const header = buildYamlExportCommentLines(options).join('\n');
  const normalizedYaml = (yamlContent ?? '').replace(/^\uFEFF/, '').replace(/^\n+/, '');

  if (normalizedYaml === '') {
    return `${header}\n`;
  }

  return `${header}\n\n${normalizedYaml}`;
};
