import test from 'node:test';
import assert from 'node:assert/strict';
import {
  prependYamlExportComment,
  getYamlExportFormatVersion,
} from '../../src/utils/yamlExportComment.ts';

test('prepends stable metadata comment lines to YAML exports', () => {
  const yamlContent = 'server:\n  instance_name: "nauthilus"\n';
  const result = prependYamlExportComment(yamlContent);

  assert.match(result, /^# Generated by Nauthilus UI\n# Export format version: 1\n\nserver:/);
  assert.ok(result.includes('instance_name: "nauthilus"'));
});

test('includes a sanitized profile line in metadata comments when provided', () => {
  const yamlContent = 'server:\n  instance_name: "nauthilus"\n';
  const result = prependYamlExportComment(yamlContent, { profileName: ' Demo \n Profile ' });

  assert.match(result, /# Profile: Demo Profile/);
  assert.ok(!result.includes('# Profile: Demo \n'));
});

test('exposes the export format version constant', () => {
  assert.equal(getYamlExportFormatVersion(), '1');
});

test('renders profile version metadata in comment headers', () => {
  const yamlContent = 'server:\n  instance_name: "nauthilus"\n';
  const result = prependYamlExportComment(yamlContent, {
    profileName: 'Demo',
    profileVersion: {
      version: 8,
      source: 'git_pull',
      createdAt: '2026-03-26T17:09:25Z',
      createdBy: 'admin',
      comment: 'Git pull main:nauthilus.yml@31b1ec5',
      metadata: {
        branch: 'main',
        filePath: 'nauthilus.yml',
        commitHash: '31b1ec5a716272fe7f22776be63f074278835621',
        repositoryUrl: 'https://alice:supersecret@example.com/repo.git?token=abc123',
      },
    },
  });

  assert.match(result, /# Version 8 • git_pull/);
  assert.match(result, /# Created: .* by admin/);
  assert.match(result, /# Comment: Git pull main:nauthilus\.yml@31b1ec5/);
  assert.match(result, /# Git: main • nauthilus\.yml • 31b1ec5a716272fe7f22776be63f074278835621 • https:\/\/\*\*\*@example\.com\/repo\.git/);
  assert.ok(!result.includes('supersecret'));
  assert.ok(!result.includes('token=abc123'));
});
